config/routes.rb
Rails.application.routes.draw do
  get 'static/log'

  root 'newspapers#index'
  resources :newspapers, only: [:index, :edit, :update, :show]
end

app/models/newspaper.rb
class Newspaper < ActiveRecord::Base
  attr_accessor :founded_at_str

  validates :name, presence: { message: 'Ajalehe nimi on kohustuslik märkida.' },
                   length: { maximum: 50, message: 'Ajalehe nimi võib olla maksimaalselt 50 sümbolit pikk.' }
  validates :founded_at, :founded_at_str, presence: { message: 'Ajalehe esimese väljaande kuupäev on kohustuslik märkida.' }

  validates_each :founded_at_str do |record, attr, value|
    unless record.errors[:founded_at_str].any?
      date = Date.strptime(value, "%d.%m.%Y") rescue false
      record.errors.add(attr, 'Ajalehe esimese väljaande kuupäev on vigasel kujul.') unless date
    end
  end

  before_save :assign_founded_at

  def assign_founded_at
    unless self.founded_at_str.nil?
      self.founded_at = Date.strptime(self.founded_at_str, "%d.%m.%Y")
    end
  end

  def founded_at_value
    founded_at_str || founded_at.strftime("%d.%m.%Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  def index
    @newspapers = Newspaper.order(:id).all
  end

  def edit
    @newspaper = Newspaper.find_by_id(params[:id])
    render :error if @newspaper.nil?
  end

  def update
    @newspaper = Newspaper.find(params[:id])

    if @newspaper.update_attributes(newspaper_params)
      flash[:success] = true
      redirect_to [:edit, @newspaper]
    else
      render :action => :edit
    end
  end

  def show
    @newspaper = Newspaper.find_by_id(params[:id])
    render json: @newspaper
  end

  private
    def newspaper_params
      params.require(:newspaper).permit(:name, :founded_at_str, :description)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def log
    render text: File.read(File.join(Rails.root, 'log', "#{Rails.env}.log")), content_type: 'text/plain'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= yield :title
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  %body
    %div(class="container")
      %div(class="row" id="content-holder")
        %ol(class="breadcrumb")
          %li= link_to 'Ajalehed', newspapers_path
          %li= link_to 'Logi', static_log_path
        %h1= yield :title
        =yield

app/views/newspapers/edit.html.haml
- content_for :title do
  Ajaleht

- if flash[:success]
  %div(class="alert alert-success alert-dismissable")
    %button(type="button" class="close" data-dismiss="alert" aria-hidden="true")
      &times;
    %p
      %strong Muudatused on edukalt salvestatud!

- if @newspaper.errors.any?
  %div(class="alert alert-danger")
    %p
      %strong Muudatuste salvestamine ebaõnnestus!
      Palun paranda allpool välja toodud vead.

= form_for @newspaper, html: { :class => "form-horizontal", :role => "form" } do |f|
  %div(class="form-group")
    %label(class="col-sm-2 control-label")
      Id:
    %div(class="col-sm-4")
      %p(class="form-control-static")= @newspaper.id

  %div{ class: ["form-group", ("has-error" if @newspaper.errors[:name].any?) ] }
    = label_tag :name, 'Nimi:', class: 'col-sm-2 control-label'
    %div(class="col-sm-4")
      = f.text_field(:name, class: 'form-control', placeholder: 'Ajalehe nimi')
    -if @newspaper.errors[:name].any?
      %div(class="col-sm-6")
        - @newspaper.errors[:name].each do |message|
          %p(class="help-block")= message

  %div{ class: ["form-group", ("has-error" if @newspaper.errors[:founded_at_str].any?) ] }
    = label_tag :founded_at_str, 'Esimene väljaanne:', class: 'col-sm-2 control-label'
    %div(class="col-sm-4")
      = f.text_field(:founded_at_str, value: @newspaper.founded_at_value, class: 'form-control', placeholder: 'PP.KK.AAAA')
    -if @newspaper.errors[:founded_at_str].any?
      %div(class="col-sm-6")
        - @newspaper.errors[:founded_at_str].each do |message|
          %p(class="help-block")= message

  %div(class="form-group")
    = label_tag :description, 'Kirjeldus:', class: 'col-sm-2 control-label'
    %div(class="col-sm-4")
      = f.text_area :description, class: 'form-control', rows: 3

  %div(class="form-group")
    %div(class="col-sm-offset-2 col-sm-4")
      = f.submit 'Salvesta', class: 'btn btn-default'

app/views/newspapers/error.html.haml
- content_for :title do
  Ajaleht

%div(class="alert alert-danger")
  %p
    %strong Viga!
    Sellise id-ga ajalehte ei ole olemas.

app/views/newspapers/index.haml
- content_for :title do
  Ajalehtede nimekiri

- if @newspapers.empty?
  %div(class="alert alert-info")
    %p
      %strong Ajalehed puuduvad.
      Rakenduses ei ole hetkel registreeritud mitte ühegi ajalehe andmeid.
- else
  %table(class="table table-striped")
    %thead
      %tr
        %th #
        %th Nimi
        %th Esimene väljaanne
        %th &nbsp;
        %th &nbsp;
    %tbody
      - @newspapers.each do |newspaper|
        %tr
          %td= newspaper.id
          %td= newspaper.name
          %td= newspaper.founded_at.strftime("%d.%m.%Y")
          %td= link_to 'Kirjeldus', '#', { :class => 'newspaper-description', :'data-id' => newspaper.id }
          %td= link_to 'Muuda', [:edit, newspaper]

app/views/newspapers/index.html.haml
- content_for :title do
  Ajalehtede nimekiri

- if @newspapers.empty?
  %div(class="alert alert-info")
    %p
      %strong Ajalehed puuduvad.
      Rakenduses ei ole hetkel registreeritud mitte ühegi ajalehe andmeid.
- else
  %table(class="table table-striped")
    %thead
      %tr
        %th #
        %th Nimi
        %th Esimene väljaanne
        %th &nbsp;
        %th &nbsp;
    %tbody
      - @newspapers.each do |newspaper|
        %tr
          %td= newspaper.id
          %td= newspaper.name
          %td= newspaper.founded_at.strftime("%d.%m.%Y")
          %td= link_to 'Kirjeldus', '#', { :class => 'newspaper-description', :'data-id' => newspaper.id }
          %td= link_to 'Muuda', [:edit, newspaper]